require 'clanomaly/checks/hwloc'
require 'clanomaly/checks/lshw'
require 'clanomaly/checks/lspci'
require 'clanomaly/checks/hwinfo'
require 'clanomaly/checks/partitions'
require 'clanomaly/checks/kernelsettings'
require 'clanomaly/checks/diskperf'
